### ISSUE TITLE
大佬，报错我看不懂！求解答！

### ISSUE THREAD

**Issue by ghost** [sqdpt666/VxMessageWeatherActions#11]
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/xiaozhushou/xiaozhushou/src/main/java/com/pt/vx/config/AllConfig.java:[88,10] illegal start of expression
Error:  /home/runner/work/xiaozhushou/xiaozhushou/src/main/java/com/pt/vx/config/AllConfig.java:[99,9] illegal start of expression
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.544 s
[INFO] Finished at: 2022-11-29T06:56:27Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project VxMessageActions: Compilation failure: Compilation failure: 
Error:  /home/runner/work/xiaozhushou/xiaozhushou/src/main/java/com/pt/vx/config/AllConfig.java:[88,10] illegal start of expression
Error:  /home/runner/work/xiaozhushou/xiaozhushou/src/main/java/com/pt/vx/config/AllConfig.java:[99,9] illegal start of expression
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.

**Comment by sqdpt666** [comment]
AllConfig.java:[88,10] illegal start of expression
AllConfig.java:[99,9] illegal start of expression
就是你的AllConfig中88行，99行有问题
